### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Maikoala** [Maikoala/furima-31943#9]
### URL
https://furima-31943.herokuapp.com/

### Basic認証のIDとパスワード |
  ID: urara
 PW: 1881
 
### 出品者用のメールアドレスとパスワード 
 mail_address: galm@test
 PW : galm1234

### 購入者用のメールアドレスとパスワード 
 mail_address: urara@test
 PW: urara4321

### 購入用カードの番号・期限・セキュリティコード 
 No: 4242424242424242
 期限: 3/24
セキュリティコード: 123

**Comment by tashu1211** [comment]
Maikoala さん、ご提出ありがとうございます‼︎

問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**

![最終課題終了_おめでとう画像1](https://user-images.githubusercontent.com/61961091/110456612-1f065a00-810d-11eb-9a01-c909f93475e5.png)
